name: Run Tests

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      api_key: "API_KEY"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Initialize Poetry project
        run: poetry install

      - name: Run Poetry project
        run: poetry run python3 -m pytest tests
